app = "crvouga-moviefinder-app-go"
primary_region = "ord"

[build]
  image = "crvouga/moviefinder-app-go:latest"

[env]
  STAGE = "production"
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
